// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaZGze7lyJoO9qYANQKk-su6EfhGtI-4U',
    appId: '1:174830733343:web:5be96c7909910f23de2d2a',
    messagingSenderId: '174830733343',
    projectId: 'flutterfire-ui-codelab-eecc0',
    authDomain: 'flutterfire-ui-codelab-eecc0.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-eecc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFrLVplfESuWIMFz97RptxtE8i1LZj67Q',
    appId: '1:174830733343:android:8821e71ef04ffd4cde2d2a',
    messagingSenderId: '174830733343',
    projectId: 'flutterfire-ui-codelab-eecc0',
    storageBucket: 'flutterfire-ui-codelab-eecc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvI8az3p7l4qSwp7sLRJ1lDTD-19Ffqm0',
    appId: '1:174830733343:ios:db769851f249077ede2d2a',
    messagingSenderId: '174830733343',
    projectId: 'flutterfire-ui-codelab-eecc0',
    storageBucket: 'flutterfire-ui-codelab-eecc0.appspot.com',
    iosClientId: '174830733343-e1u41i6brp9nu6mqf6jkkd0e71s9nff5.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvI8az3p7l4qSwp7sLRJ1lDTD-19Ffqm0',
    appId: '1:174830733343:ios:6e2d5f817cfc6af0de2d2a',
    messagingSenderId: '174830733343',
    projectId: 'flutterfire-ui-codelab-eecc0',
    storageBucket: 'flutterfire-ui-codelab-eecc0.appspot.com',
    iosClientId: '174830733343-fvm94a3jb640npjdl9fj49igk49aldrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
